/**
 * Charan AI Document Exporter (PDF, Excel/CSV, JSON & TXT)
 */

export function downloadAsPDF(title: string, content: string) {
  if (typeof window === 'undefined') return;

  // Format content as clean printable HTML
  const htmlContent = `
    <!DOCTYPE html>
    <html>
      <head>
        <title>${title}</title>
        <style>
          body {
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
            padding: 40px;
            color: #111;
            line-height: 1.6;
          }
          h1 { color: #d97706; border-bottom: 2px solid #f59e0b; padding-bottom: 8px; }
          pre { background: #f4f4f5; padding: 12px; border-radius: 6px; overflow-x: auto; }
          code { font-family: monospace; }
          .footer { margin-top: 40px; font-size: 12px; color: #71717a; border-top: 1px solid #e4e4e7; padding-top: 12px; }
        </style>
      </head>
      <body>
        <h1>${title}</h1>
        <div>${content.replace(/\n/g, '<br/>')}</div>
        <div class="footer">Generated by Charan AI • ${new Date().toLocaleString()}</div>
      </body>
    </html>
  `;

  const printWindow = window.open('', '_blank');
  if (printWindow) {
    printWindow.document.write(htmlContent);
    printWindow.document.close();
    printWindow.focus();
    setTimeout(() => {
      printWindow.print();
    }, 250);
  }
}

export function downloadAsCSV(filename: string, textContent: string) {
  if (typeof window === 'undefined') return;

  const lines = textContent.split('\n');
  const csvRows: string[] = [];

  lines.forEach((line) => {
    if (line.includes('|')) {
      const row = line
        .split('|')
        .map((cell) => `"${cell.trim().replace(/"/g, '""')}"`)
        .filter((cell, idx, arr) => idx > 0 && idx < arr.length - 1)
        .join(',');
      if (row.length > 0 && !row.includes('---')) {
        csvRows.push(row);
      }
    }
  });

  const csvData = csvRows.length > 0 ? csvRows.join('\n') : `"Content"\n"${textContent.replace(/"/g, '""')}"`;

  const blob = new Blob([csvData], { type: 'text/csv;charset=utf-8;' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.setAttribute('href', url);
  link.setAttribute('download', `${filename.toLowerCase().replace(/\s+/g, '_')}.csv`);
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
}

export function downloadAsJSON(filename: string, textContent: string) {
  if (typeof window === 'undefined') return;

  let jsonString = '';
  try {
    const jsonMatch = textContent.match(/```json\s*([\s\S]*?)\s*```/);
    if (jsonMatch && jsonMatch[1]) {
      const parsed = JSON.parse(jsonMatch[1]);
      jsonString = JSON.stringify(parsed, null, 2);
    } else {
      const parsed = JSON.parse(textContent);
      jsonString = JSON.stringify(parsed, null, 2);
    }
  } catch (e) {
    jsonString = JSON.stringify(
      {
        generator: 'Charan AI',
        date: new Date().toISOString(),
        content: textContent,
      },
      null,
      2
    );
  }

  const blob = new Blob([jsonString], { type: 'application/json' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.setAttribute('href', url);
  link.setAttribute('download', `${filename.toLowerCase().replace(/\s+/g, '_')}.json`);
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
}

export function downloadAsTXT(filename: string, textContent: string) {
  if (typeof window === 'undefined') return;

  const blob = new Blob([textContent], { type: 'text/plain;charset=utf-8;' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.setAttribute('href', url);
  link.setAttribute('download', `${filename.toLowerCase().replace(/\s+/g, '_')}.txt`);
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
}
